[package]
name = "void_proof"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
ratatui = "0.23.0"
crossterm = "0.28"
once_cell = "1.20.2"
num_cpus = "1.16.0"

[dev-dependencies]
test-case = "3.3"
