[package]
name = "network_simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"  # Adjust the version as needed
crossterm = "0.28"  # Adjust the version as needed
rand = "0.8.5"
indicatif = "0.17.8"
