[package]
name = "tri_simulation"
version = "0.1.0"
edition = "2021"
default-run = "tri_simulation"

[[bin]]
name = "tri_simulation"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
once_cell = "1.20.2"
